[tool.poetry]
name = "pytemplate"
version = "1.0.1"
description = "Escape Python Template Project"
authors = ["Escape Technologies SAS <ping@escape.tech>"]
maintainers = [
    "Swan <swan@escape.tech>",
    "Antoine Carossio <antoine@escape.tech>"
]
license = "MIT"
packages = [
    { include = "pytemplate" }
]
readme = "README.md"
"homepage" = "https://escape.tech/"
"repository" = "https://github.com/Escape-Technologies/python-project-template"

[tool.poetry.scripts]
pytemplate-cli = 'pytemplate:main'


[tool.poetry.dependencies]
python = ">=3.7,<=3.11"

[tool.poetry.dev-dependencies]
autoflake = "^1.7"
docformatter = "^1.5"
isort = "^5.11.5"
mypy = "^1.0"
poetryup = "^0.12.3"
pylint = "^2.13.9"
pylint-absolute-imports = "1.0.1"
pylint-quotes = "^0.2.3"
pytest = "^7.2.0"
pytest-cov = "^4.0.0"
pytest-mock = "^3.10.0"
setuptools = "^66"
unify = "^0.5"
vulture = "^2.6"
yamllint = "^1.28.0"
yapf = "^0.32.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

