[tool.poetry]
name = "pytemplate"
version = "1.0.1"
description = "Escape Python Template Project"
authors = ["Escape Technologies SAS <ping@escape.tech>"]
maintainers = [
    "Swan <swan@escape.tech>",
    "Antoine Carossio <antoine@escape.tech>"
]
license = "MIT"
packages = [
    { include = "pytemplate" }
]
include = [
    "LICENSE",
]
readme = "README.md"
"homepage" = "https://escape.tech/"
"repository" = "https://github.com/Escape-Technologies/python-project-template"

[tool.poetry.scripts]
pytemplate-cli = 'pytemplate:main'


[tool.poetry.dependencies]
python = ">=3.7,<=3.11"

[tool.poetry.dev-dependencies]
autoflake = "^1.4"
docformatter = "^1.4"
isort = "^5.10.1"
mypy = "^0.950"
poetryup = "^0.3.15"
pylint = "^2.13.9"
pylint-absolute-imports = "1.0.1"
pylint-quotes = "^0.2.3"
pytest = "^6.2.5"
pytest-cov = "^2.12.1"
pytest-mock = "^3.8.2"
setuptools = "^45"
unify = "^0.5"
vulture = "^2.5"
yamllint = "^1.27.1"
yapf = "^0.31.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

