name: CI

"on":
  push:
  pull_request:
    types: [opened, reopened]

env:
  MODULE_NAME: app # Edit the name of the module here
  MIN_TEST_COV: 0 # Edit your min coverage here

jobs:
  CI:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
        python-version: ["3.10", "3.11", "3.12", "3.13"]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install -U uv
      - name: Setup uv
        run: |
          uv venv
          uv sync
      - name: Run lint
        if: always()
        run: |
          uv run yamllint --version
          uv run yamllint . -s
          uv run mdformat --version
          uv run mdformat .
          uv run ruff --version
          uv run ruff check $MODULE_NAME tests --fix
          uv run ruff format $MODULE_NAME tests
          uv run mypy --version
          uv run mypy $MODULE_NAME tests
      - name: Run tests
        run: |
          uv run pytest --cov=$MODULE_NAME --cov-report=xml --cov-fail-under=$MIN_TEST_COV tests/unit
      # - name: Upload coverage to Codecov
      #   uses: codecov/codecov-action@v2
      #   with:
      #     token: ${{ secrets.CODECOV_TOKEN }}
      #     files: ./coverage.xml
      #     flags: unittests
